version: "3.9"
name: pulse-hub

services:
  # otel-collector:
  #   image: otel/opentelemetry-collector-contrib:0.96.0
  #   command: ["--config=/etc/otel-collector.yaml"]
  #   volumes:
  #     - ./otel-collector.yaml:/etc/otel-collector.yaml
  #   ports:
  #     - "4317:4317"   # OTLP gRPC
  #     - "4318:4318"   # OTLP HTTP
  #     - "9464:9464"   # Prometheus metrics
  #   depends_on:
  #     - jaeger

  # jaeger:
  #   image: jaegertracing/all-in-one:1.55
  #   ports:
  #     - "16686:16686"
  #     - "14250:14250"

  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: prometheus
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    volumes:
      - ./infra/prometheus/config.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:2.9.6
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yaml
    volumes:
      - ./infra/loki/config.yaml:/etc/loki/loki.yaml
      - ./loki-data:/loki

  promtail:
    image: grafana/promtail:2.9.6
    container_name: promtail
    volumes:
      - ./infra/promtail/config.yaml:/etc/promtail/promtail.yaml
      - ./logs:/var/log/app:ro
    command: -config.file=/etc/promtail/promtail.yaml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-clock-panel
    depends_on:
      - loki

  broker:
    image: apache/kafka:latest
    container_name: kafka-broker
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

  db-postgres:
    image: postgres:15
    container_name: db-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    
  db-redis:
    image: redis:8.4.0
    container_name: db-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
