version: "3.9"

services:
  # otel-collector:
  #   image: otel/opentelemetry-collector-contrib:0.96.0
  #   command: ["--config=/etc/otel-collector.yaml"]
  #   volumes:
  #     - ./otel-collector.yaml:/etc/otel-collector.yaml
  #   ports:
  #     - "4317:4317"   # OTLP gRPC
  #     - "4318:4318"   # OTLP HTTP
  #     - "9464:9464"   # Prometheus metrics
  #   depends_on:
  #     - jaeger

  # jaeger:
  #   image: jaegertracing/all-in-one:1.55
  #   ports:
  #     - "16686:16686"
  #     - "14250:14250"

  # prometheus:
  #   image: prom/prometheus:v2.51.2
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"

  broker:
    image: apache/kafka:latest
    container_name: kafka-broker
    ports:
      - "9092:9092"  # Важно: пробрасываем порт на хост
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092  # Для хоста
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
