postgres:
  image:
    repository: bitnami/postgresql

  architecture: standalone

  auth:
    username: analyzer-user
    password: analyzer-password
    database: analyzer

  primary:
    persistence:
      enabled: false
