server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: analyzer-service
    static_configs:
      - targets:
          - localhost
        labels:
          service: analyzer
          env: local
          __path__: /var/log/app/analyzer-service.log

    pipeline_stages:
      - json:
          expressions:
            level: levelname
            logger: name
            trace_id: trace_id
            span_id: span_id
      - labels:
          level:

  - job_name: api-service
    static_configs:
      - targets:
          - localhost
        labels:
          service: api
          env: local
          __path__: /var/log/app/api-service.log

    pipeline_stages:
      - json:
          expressions:
            level: levelname
            logger: name
            trace_id: trace_id
            span_id: span_id
      - labels:
          level:

  - job_name: crawler-service
    static_configs:
      - targets:
          - localhost
        labels:
          service: crawler
          env: local
          __path__: /var/log/app/crawler-service.log

    pipeline_stages:
      - json:
          expressions:
            level: levelname
            logger: name
            trace_id: trace_id
            span_id: span_id
      - labels:
          level: