---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-service"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ .Release.Name }}-{{ .Chart.Name }}-service"
spec:
  type: "ClusterIP"
  ports:
    - targetPort: {{ .Values.service.httpPort }}
      port: {{ .Values.service.httpPort }}
      protocol: TCP
      name: http
    - targetPort: {{ .Values.service.grpcPort }}
      port: {{ .Values.service.grpcPort }}
      protocol: TCP
      name: grpc
  selector:
    app: "{{ .Release.Name }}-{{ .Chart.Name }}"
