global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "api-service"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "host.docker.internal:9000"
  
  - job_name: "crawler-service"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "host.docker.internal:9001"

  - job_name: "analyzer-service"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "host.docker.internal:9002"
