---
apiVersion: v2
type: application
name: pulse-hub
description: A Helm chart for deploying the Pulse Hub application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: opentelemetry-collector
    version: 0.145.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
