service-api:
  replicaCount: 1
  image:
    repository: "pulse-hub/service-api"
    tag: "latest"
    pullPolicy: "IfNotPresent"
  service:
    port: 8080
  ingress:
    host: api.pulse-hub.local
  config:
    TRACE_EXPORTER__IS_ENABLED: "true"
    TRACE_EXPORTER__OTLP_ENDPOINT: "http://pulse-hub-otel-collector:4317"
    METRICS_EXPORTER__IS_ENABLED: "true"
    METRICS_EXPORTER__OTLP_ENDPOINT: "http://pulse-hub-otel-collector:4317"
    LOGGING__IS_EXPORT_ENABLED: "true"
    LOGGING__EXPORTING_ENDPOINT: "http://pulse-hub-otel-collector:4317"
    HTTP_SERVER__PORT: "8080"
    ANALYZER_CLIENT__ADDRESS: "analyzer:50051"
    CRAWLER_CLIENT__ADDRESS: "crawler:50051"

service-crawler:
  replicaCount: 1
  image:
    repository: "pulse-hub/service-crawler"
    tag: "latest"
    pullPolicy: "IfNotPresent"
  service:
    httpPort: 8080
    grpcPort: 50051
  config:
    TRACE_EXPORTER__IS_ENABLED: "true"
    TRACE_EXPORTER__OTLP_ENDPOINT: "http://pulse-hub-otel-collector:4317"
    METRICS_EXPORTER__IS_ENABLED: "true"
    METRICS_EXPORTER__OTLP_ENDPOINT: "http://pulse-hub-otel-collector:4317"
    LOGGING__IS_EXPORT_ENABLED: "true"
    LOGGING__EXPORTING_ENDPOINT: "http://pulse-hub-otel-collector:4317"
    HTTP_SERVER__PORT: "8080"
    GRPC_SERVER__PORT: "50051"
    REDIS__HOST: "pulse-hub-redis"
    REDIS__PORT: "6379"
    REDIS__PASSWORD: ""
    REDIS__DATABASE: "0"
    KAFKA_PRODUCER__BOOTSTRAP_SERVERS: "pulse-hub-kafka:9092"
    KAFKA_PRODUCER__TOPIC: "spans"
    CRAWLER_CONCURRENT_WORKERS: "1"

